
classdef ObjRecognised < ros.Message
    %ObjRecognised MATLAB implementation of obj_tf/ObjRecognised
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'obj_tf/ObjRecognised' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'dce02b7de2874b19e0b00ae776e4cb9c' % The MD5 Checksum of the message definition
        PropertyList = { 'DetectedTime' 'X' 'Y' 'Z' } % List of non-constant message properties
        ROSPropertyList = { 'detectedTime' 'x' 'y' 'z' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.Time' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        DetectedTime
        X
        Y
        Z
    end
    methods
        function set.DetectedTime(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.Time'};
            validateattributes(val, validClasses, validAttributes, 'ObjRecognised', 'DetectedTime')
            obj.DetectedTime = val;
        end
        function set.X(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ObjRecognised', 'X');
            obj.X = single(val);
        end
        function set.Y(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ObjRecognised', 'Y');
            obj.Y = single(val);
        end
        function set.Z(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ObjRecognised', 'Z');
            obj.Z = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.obj_tf.ObjRecognised.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.obj_tf.ObjRecognised;
            obj.reload(strObj);
        end
    end
end
