
classdef ChangeHardwareVersionRequest < ros.Message
    %ChangeHardwareVersionRequest MATLAB implementation of niryo_one_msgs/ChangeHardwareVersionRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ChangeHardwareVersionRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f6d236e359b4916a65b178643f25ed07' % The MD5 Checksum of the message definition
        PropertyList = { 'OldVersion' 'NewVersion' } % List of non-constant message properties
        ROSPropertyList = { 'old_version' 'new_version' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        OldVersion
        NewVersion
    end
    methods
        function set.OldVersion(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ChangeHardwareVersionRequest', 'OldVersion');
            obj.OldVersion = int32(val);
        end
        function set.NewVersion(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ChangeHardwareVersionRequest', 'NewVersion');
            obj.NewVersion = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ChangeHardwareVersionRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ChangeHardwareVersionRequest;
            obj.reload(strObj);
        end
    end
end
