
classdef CloseGripperRequest < ros.Message
    %CloseGripperRequest MATLAB implementation of niryo_one_msgs/CloseGripperRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/CloseGripperRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '44ae3b67a5ebbc045039caba07d974fa' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'ClosePosition' 'CloseSpeed' 'CloseHoldTorque' 'CloseMaxTorque' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'close_position' 'close_speed' 'close_hold_torque' 'close_max_torque' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        ClosePosition
        CloseSpeed
        CloseHoldTorque
        CloseMaxTorque
    end
    methods
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CloseGripperRequest', 'Id');
            obj.Id = uint8(val);
        end
        function set.ClosePosition(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CloseGripperRequest', 'ClosePosition');
            obj.ClosePosition = int16(val);
        end
        function set.CloseSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CloseGripperRequest', 'CloseSpeed');
            obj.CloseSpeed = int16(val);
        end
        function set.CloseHoldTorque(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CloseGripperRequest', 'CloseHoldTorque');
            obj.CloseHoldTorque = int16(val);
        end
        function set.CloseMaxTorque(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'CloseGripperRequest', 'CloseMaxTorque');
            obj.CloseMaxTorque = int16(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.CloseGripperRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.CloseGripperRequest;
            obj.reload(strObj);
        end
    end
end
