
classdef ConveyorFeedback < ros.Message
    %ConveyorFeedback MATLAB implementation of niryo_one_msgs/ConveyorFeedback
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ConveyorFeedback' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1e7764cd998f86f936c67fc5b79bd288' % The MD5 Checksum of the message definition
        PropertyList = { 'ConveyorId' 'ConnectionState' 'Running' 'Speed' 'Direction' } % List of non-constant message properties
        ROSPropertyList = { 'conveyor_id' 'connection_state' 'running' 'speed' 'direction' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ConveyorId
        ConnectionState
        Running
        Speed
        Direction
    end
    methods
        function set.ConveyorId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ConveyorFeedback', 'ConveyorId');
            obj.ConveyorId = uint8(val);
        end
        function set.ConnectionState(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ConveyorFeedback', 'ConnectionState');
            obj.ConnectionState = logical(val);
        end
        function set.Running(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ConveyorFeedback', 'Running');
            obj.Running = logical(val);
        end
        function set.Speed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ConveyorFeedback', 'Speed');
            obj.Speed = int16(val);
        end
        function set.Direction(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ConveyorFeedback', 'Direction');
            obj.Direction = int8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ConveyorFeedback.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ConveyorFeedback;
            obj.reload(strObj);
        end
    end
end
