
classdef DebugColorDetectionResponse < ros.Message
    %DebugColorDetectionResponse MATLAB implementation of niryo_one_msgs/DebugColorDetectionResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/DebugColorDetectionResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'c43bfac92109bcd6baf5c9acaab4d069' % The MD5 Checksum of the message definition
        PropertyList = { 'Img' } % List of non-constant message properties
        ROSPropertyList = { 'img' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msg.sensor_msgs.CompressedImage' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Img
    end
    methods
        function set.Img(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.sensor_msgs.CompressedImage'};
            validateattributes(val, validClasses, validAttributes, 'DebugColorDetectionResponse', 'Img')
            obj.Img = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.DebugColorDetectionResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.DebugColorDetectionResponse;
            obj.reload(strObj);
        end
    end
end
