
classdef EditWorkspaceRequest < ros.Message
    %EditWorkspaceRequest MATLAB implementation of niryo_one_msgs/EditWorkspaceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/EditWorkspaceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ba9b3580344c5b5274fc4771afa1010d' % The MD5 Checksum of the message definition
        PropertyList = { 'PoseOrigin' 'Pose1' 'Pose2' 'Pose3' 'Cmd' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'pose_origin' 'pose_1' 'pose_2' 'pose_3' 'cmd' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.RobotState' ...
			 'ros.msggen.niryo_one_msgs.RobotState' ...
			 'ros.msggen.niryo_one_msgs.RobotState' ...
			 'ros.msggen.niryo_one_msgs.RobotState' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
        CREATE = int32(1)
        REMOVE = int32(-1)
    end
    properties
        PoseOrigin
        Pose1
        Pose2
        Pose3
        Cmd
        Name
    end
    methods
        function set.PoseOrigin(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'PoseOrigin')
            obj.PoseOrigin = val;
        end
        function set.Pose1(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'Pose1')
            obj.Pose1 = val;
        end
        function set.Pose2(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'Pose2')
            obj.Pose2 = val;
        end
        function set.Pose3(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'Pose3')
            obj.Pose3 = val;
        end
        function set.Cmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'Cmd');
            obj.Cmd = int32(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'EditWorkspaceRequest', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.EditWorkspaceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.EditWorkspaceRequest;
            obj.reload(strObj);
        end
    end
end
