
classdef generatetrajResponse < ros.Message
    %generatetrajResponse MATLAB implementation of niryo_one_msgs/generatetrajResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/generatetrajResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ba7b3e631331bbda0feb216a3c8bf46e' % The MD5 Checksum of the message definition
        PropertyList = { 'Positions' 'Velocities' 'Acceleration' } % List of non-constant message properties
        ROSPropertyList = { 'positions' 'velocities' 'acceleration' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Positions
        Velocities
        Acceleration
    end
    methods
        function set.Positions(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'generatetrajResponse', 'Positions');
            obj.Positions = double(val);
        end
        function set.Velocities(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'generatetrajResponse', 'Velocities');
            obj.Velocities = double(val);
        end
        function set.Acceleration(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'generatetrajResponse', 'Acceleration');
            obj.Acceleration = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.generatetrajResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.generatetrajResponse;
            obj.reload(strObj);
        end
    end
end
