
classdef GetCalibrationCamResponse < ros.Message
    %GetCalibrationCamResponse MATLAB implementation of niryo_one_msgs/GetCalibrationCamResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetCalibrationCamResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b839fe4c8d129bfa9bec199fe2fd8ec6' % The MD5 Checksum of the message definition
        PropertyList = { 'CameraInfo' 'IsSet' } % List of non-constant message properties
        ROSPropertyList = { 'camera_info' 'is_set' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.sensor_msgs.CameraInfo' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CameraInfo
        IsSet
    end
    methods
        function set.CameraInfo(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sensor_msgs.CameraInfo'};
            validateattributes(val, validClasses, validAttributes, 'GetCalibrationCamResponse', 'CameraInfo')
            obj.CameraInfo = val;
        end
        function set.IsSet(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GetCalibrationCamResponse', 'IsSet');
            obj.IsSet = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetCalibrationCamResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetCalibrationCamResponse;
            obj.reload(strObj);
        end
    end
end
