
classdef GetCalibrationCamRequest < ros.Message
    %GetCalibrationCamRequest MATLAB implementation of niryo_one_msgs/GetCalibrationCamRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetCalibrationCamRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6aac6c697d5414bc0fcede8c33981d0e' % The MD5 Checksum of the message definition
        PropertyList = { 'Empty' } % List of non-constant message properties
        ROSPropertyList = { 'empty' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Empty' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Empty
    end
    methods
        function set.Empty(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Empty'};
            validateattributes(val, validClasses, validAttributes, 'GetCalibrationCamRequest', 'Empty')
            obj.Empty = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetCalibrationCamRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetCalibrationCamRequest;
            obj.reload(strObj);
        end
    end
end
