
classdef GetTrajectoryListResponse < ros.Message
    %GetTrajectoryListResponse MATLAB implementation of niryo_one_msgs/GetTrajectoryListResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetTrajectoryListResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '9e3d487bb28329ff7afe413fe117bc56' % The MD5 Checksum of the message definition
        PropertyList = { 'Trajectories' } % List of non-constant message properties
        ROSPropertyList = { 'trajectories' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Trajectory' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Trajectories
    end
    methods
        function set.Trajectories(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.niryo_one_msgs.Trajectory.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.niryo_one_msgs.Trajectory'};
            validateattributes(val, validClasses, validAttributes, 'GetTrajectoryListResponse', 'Trajectories')
            obj.Trajectories = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetTrajectoryListResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetTrajectoryListResponse;
            obj.reload(strObj);
        end
    end
end
