
classdef GetWorkspaceRatioResponse < ros.Message
    %GetWorkspaceRatioResponse MATLAB implementation of niryo_one_msgs/GetWorkspaceRatioResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetWorkspaceRatioResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8735052c4a4ebfd096e50f820465af6f' % The MD5 Checksum of the message definition
        PropertyList = { 'Status' 'Message' 'Ratio' } % List of non-constant message properties
        ROSPropertyList = { 'status' 'message' 'ratio' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Status
        Message
        Ratio
    end
    methods
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GetWorkspaceRatioResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetWorkspaceRatioResponse', 'Message');
            obj.Message = char(val);
        end
        function set.Ratio(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GetWorkspaceRatioResponse', 'Ratio');
            obj.Ratio = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetWorkspaceRatioResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetWorkspaceRatioResponse;
            obj.reload(strObj);
        end
    end
end
