
classdef GetWorkspaceRobotPosesRequest < ros.Message
    %GetWorkspaceRobotPosesRequest MATLAB implementation of niryo_one_msgs/GetWorkspaceRobotPosesRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetWorkspaceRobotPosesRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'a4c8afcaa65fb464384c5579b2744fb0' % The MD5 Checksum of the message definition
        PropertyList = { 'Workspace' } % List of non-constant message properties
        ROSPropertyList = { 'workspace' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Workspace
    end
    methods
        function set.Workspace(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetWorkspaceRobotPosesRequest', 'Workspace');
            obj.Workspace = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetWorkspaceRobotPosesRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetWorkspaceRobotPosesRequest;
            obj.reload(strObj);
        end
    end
end
