
classdef GetWorkspaceListResponse < ros.Message
    %GetWorkspaceListResponse MATLAB implementation of niryo_one_msgs/GetWorkspaceListResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetWorkspaceListResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8b36c598e23fd962676550874c6879f7' % The MD5 Checksum of the message definition
        PropertyList = { 'Workspaces' } % List of non-constant message properties
        ROSPropertyList = { 'workspaces' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Workspaces
    end
    methods
        function set.Workspaces(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'GetWorkspaceListResponse', 'Workspaces');
            obj.Workspaces = cell(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetWorkspaceListResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetWorkspaceListResponse;
            obj.reload(strObj);
        end
    end
end
