
classdef ManageTrajectoryRequest < ros.Message
    %ManageTrajectoryRequest MATLAB implementation of niryo_one_msgs/ManageTrajectoryRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManageTrajectoryRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '66bbf6ab6eda366ac1dd8715ac3a4eb4' % The MD5 Checksum of the message definition
        PropertyList = { 'Trajectory' 'CmdType' 'TrajectoryId' } % List of non-constant message properties
        ROSPropertyList = { 'trajectory' 'cmd_type' 'trajectory_id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Trajectory' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Trajectory
        CmdType
        TrajectoryId
    end
    methods
        function set.Trajectory(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.Trajectory'};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryRequest', 'Trajectory')
            obj.Trajectory = val;
        end
        function set.CmdType(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryRequest', 'CmdType');
            obj.CmdType = int32(val);
        end
        function set.TrajectoryId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryRequest', 'TrajectoryId');
            obj.TrajectoryId = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManageTrajectoryRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManageTrajectoryRequest;
            obj.reload(strObj);
        end
    end
end
