
classdef ManageProcessRequest < ros.Message
    %ManageProcessRequest MATLAB implementation of niryo_one_msgs/ManageProcessRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManageProcessRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'dd8b2aafceb70a34ba694d0f5e0b1623' % The MD5 Checksum of the message definition
        PropertyList = { 'Action' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'action' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Action
        Name
    end
    methods
        function set.Action(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageProcessRequest', 'Action');
            obj.Action = uint8(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ManageProcessRequest', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManageProcessRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManageProcessRequest;
            obj.reload(strObj);
        end
    end
end
