
classdef ManageSequenceRequest < ros.Message
    %ManageSequenceRequest MATLAB implementation of niryo_one_msgs/ManageSequenceRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManageSequenceRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'da644ff8e5065e5598b50f9f1180dd4c' % The MD5 Checksum of the message definition
        PropertyList = { 'Sequence' 'CmdType' 'SequenceId' } % List of non-constant message properties
        ROSPropertyList = { 'sequence' 'cmd_type' 'sequence_id' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Sequence' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Sequence
        CmdType
        SequenceId
    end
    methods
        function set.Sequence(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.Sequence'};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceRequest', 'Sequence')
            obj.Sequence = val;
        end
        function set.CmdType(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceRequest', 'CmdType');
            obj.CmdType = int32(val);
        end
        function set.SequenceId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceRequest', 'SequenceId');
            obj.SequenceId = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManageSequenceRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManageSequenceRequest;
            obj.reload(strObj);
        end
    end
end
