
classdef ManagePositionResponse < ros.Message
    %ManagePositionResponse MATLAB implementation of niryo_one_msgs/ManagePositionResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManagePositionResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '0bfc71def0391c7cb33d092741f6f696' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Position' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        Status
        Message
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.Position'};
            validateattributes(val, validClasses, validAttributes, 'ManagePositionResponse', 'Position')
            obj.Position = val;
        end
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManagePositionResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ManagePositionResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManagePositionResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManagePositionResponse;
            obj.reload(strObj);
        end
    end
end
