
classdef ProcessState < ros.Message
    %ProcessState MATLAB implementation of niryo_one_msgs/ProcessState
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ProcessState' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ea4d2ab332d89d84ef08a4d6fe541702' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'IsActive' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'is_active' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        IsActive
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'cell', 'string'};
            if isempty(val)
                % Allow empty [] input
                val = cell.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ProcessState', 'Name');
            obj.Name = cell(val);
        end
        function set.IsActive(obj, val)
            validClasses = {'logical', 'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = logical.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ProcessState', 'IsActive');
            obj.IsActive = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ProcessState.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ProcessState;
            obj.reload(strObj);
        end
    end
end
