
classdef RobotMoveRequest < ros.Message
    %RobotMoveRequest MATLAB implementation of niryo_one_msgs/RobotMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/RobotMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3321176c3f74bd24007c3dea8f6db7dc' % The MD5 Checksum of the message definition
        PropertyList = { 'Cmd' } % List of non-constant message properties
        ROSPropertyList = { 'cmd' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.RobotMoveCommand' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Cmd
    end
    methods
        function set.Cmd(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotMoveCommand'};
            validateattributes(val, validClasses, validAttributes, 'RobotMoveRequest', 'Cmd')
            obj.Cmd = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.RobotMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.RobotMoveRequest;
            obj.reload(strObj);
        end
    end
end
