
classdef SetBoolRequest < ros.Message
    %SetBoolRequest MATLAB implementation of niryo_one_msgs/SetBoolRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/SetBoolRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'e431d687bf4b2c65fbd94b12ae0cb5d9' % The MD5 Checksum of the message definition
        PropertyList = { 'Value' } % List of non-constant message properties
        ROSPropertyList = { 'value' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Value
    end
    methods
        function set.Value(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetBoolRequest', 'Value');
            obj.Value = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.SetBoolRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.SetBoolRequest;
            obj.reload(strObj);
        end
    end
end
