
classdef SetLedsRequest < ros.Message
    %SetLedsRequest MATLAB implementation of niryo_one_msgs/SetLedsRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/SetLedsRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5dd1053b3769329bd3895728a55810d3' % The MD5 Checksum of the message definition
        PropertyList = { 'Values' } % List of non-constant message properties
        ROSPropertyList = { 'values' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Values
    end
    methods
        function set.Values(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'SetLedsRequest', 'Values');
            obj.Values = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.SetLedsRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.SetLedsRequest;
            obj.reload(strObj);
        end
    end
end
