
classdef SetSequenceAutorunResponse < ros.Message
    %SetSequenceAutorunResponse MATLAB implementation of niryo_one_msgs/SetSequenceAutorunResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/SetSequenceAutorunResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2c1d00fb8b4e78420f43d93d5292a429' % The MD5 Checksum of the message definition
        PropertyList = { 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Status
        Message
    end
    methods
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetSequenceAutorunResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SetSequenceAutorunResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.SetSequenceAutorunResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.SetSequenceAutorunResponse;
            obj.reload(strObj);
        end
    end
end
