
classdef ShiftPose < ros.Message
    %ShiftPose MATLAB implementation of niryo_one_msgs/ShiftPose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ShiftPose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '1582f6063ca2d2749f4798d853f452ac' % The MD5 Checksum of the message definition
        PropertyList = { 'AxisNumber' 'Value' } % List of non-constant message properties
        ROSPropertyList = { 'axis_number' 'value' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        AxisNumber
        Value
    end
    methods
        function set.AxisNumber(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ShiftPose', 'AxisNumber');
            obj.AxisNumber = int32(val);
        end
        function set.Value(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ShiftPose', 'Value');
            obj.Value = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ShiftPose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ShiftPose;
            obj.reload(strObj);
        end
    end
end
