
classdef ChangeMotorConfigRequest < ros.Message
    %ChangeMotorConfigRequest MATLAB implementation of niryo_one_msgs/ChangeMotorConfigRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ChangeMotorConfigRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '6e2ce6fc69b92fe327fc570d69342705' % The MD5 Checksum of the message definition
        PropertyList = { 'CanRequiredMotorIdList' 'DxlRequiredMotorIdList' } % List of non-constant message properties
        ROSPropertyList = { 'can_required_motor_id_list' 'dxl_required_motor_id_list' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        CanRequiredMotorIdList
        DxlRequiredMotorIdList
    end
    methods
        function set.CanRequiredMotorIdList(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ChangeMotorConfigRequest', 'CanRequiredMotorIdList');
            obj.CanRequiredMotorIdList = int32(val);
        end
        function set.DxlRequiredMotorIdList(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = int32.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'ChangeMotorConfigRequest', 'DxlRequiredMotorIdList');
            obj.DxlRequiredMotorIdList = int32(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ChangeMotorConfigRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ChangeMotorConfigRequest;
            obj.reload(strObj);
        end
    end
end
