
classdef DebugColorDetectionRequest < ros.Message
    %DebugColorDetectionRequest MATLAB implementation of niryo_one_msgs/DebugColorDetectionRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/DebugColorDetectionRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '89e44dcab627a2c43a70ae1100695caa' % The MD5 Checksum of the message definition
        PropertyList = { 'Color' } % List of non-constant message properties
        ROSPropertyList = { 'color' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Color
    end
    methods
        function set.Color(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'DebugColorDetectionRequest', 'Color');
            obj.Color = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.DebugColorDetectionRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.DebugColorDetectionRequest;
            obj.reload(strObj);
        end
    end
end
