
classdef EditGripRequest < ros.Message
    %EditGripRequest MATLAB implementation of niryo_one_msgs/EditGripRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/EditGripRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7078678693328ee7a9f469bbae1863c3' % The MD5 Checksum of the message definition
        PropertyList = { 'RobotPose' 'Cmd' 'Name' 'Workspace' } % List of non-constant message properties
        ROSPropertyList = { 'robot_pose' 'cmd' 'name' 'workspace' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.RobotState' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
        CREATE = int32(1)
        REMOVE = int32(-1)
    end
    properties
        RobotPose
        Cmd
        Name
        Workspace
    end
    methods
        function set.RobotPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'EditGripRequest', 'RobotPose')
            obj.RobotPose = val;
        end
        function set.Cmd(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'EditGripRequest', 'Cmd');
            obj.Cmd = int32(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'EditGripRequest', 'Name');
            obj.Name = char(val);
        end
        function set.Workspace(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'EditGripRequest', 'Workspace');
            obj.Workspace = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.EditGripRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.EditGripRequest;
            obj.reload(strObj);
        end
    end
end
