
classdef generatetrajRequest < ros.Message
    %generatetrajRequest MATLAB implementation of niryo_one_msgs/generatetrajRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/generatetrajRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '051b5bff87455932261d52e3288227b1' % The MD5 Checksum of the message definition
        PropertyList = { 'J0' 'J1' } % List of non-constant message properties
        ROSPropertyList = { 'j0' 'j1' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        J0
        J1
    end
    methods
        function set.J0(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'generatetrajRequest', 'J0');
            obj.J0 = double(val);
        end
        function set.J1(obj, val)
            validClasses = {'numeric'};
            if isempty(val)
                % Allow empty [] input
                val = double.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validateattributes(val, validClasses, validAttributes, 'generatetrajRequest', 'J1');
            obj.J1 = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.generatetrajRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.generatetrajRequest;
            obj.reload(strObj);
        end
    end
end
