
classdef GetSequenceListResponse < ros.Message
    %GetSequenceListResponse MATLAB implementation of niryo_one_msgs/GetSequenceListResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetSequenceListResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8b17e9078cd2c2cefb602b6ae4528eba' % The MD5 Checksum of the message definition
        PropertyList = { 'Sequences' } % List of non-constant message properties
        ROSPropertyList = { 'sequences' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Sequence' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Sequences
    end
    methods
        function set.Sequences(obj, val)
            if isempty(val)
                % Allow empty [] input
                val = ros.msggen.niryo_one_msgs.Sequence.empty(0, 1);
            end
            val = val(:);
            validAttributes = {'vector'};
            validClasses = {'ros.msggen.niryo_one_msgs.Sequence'};
            validateattributes(val, validClasses, validAttributes, 'GetSequenceListResponse', 'Sequences')
            obj.Sequences = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetSequenceListResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetSequenceListResponse;
            obj.reload(strObj);
        end
    end
end
