
classdef GetTargetPoseResponse < ros.Message
    %GetTargetPoseResponse MATLAB implementation of niryo_one_msgs/GetTargetPoseResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/GetTargetPoseResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '9b7a24f6dc34ac098e250d656dd24cb1' % The MD5 Checksum of the message definition
        PropertyList = { 'TargetPose' 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'target_pose' 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.RobotState' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        TargetPose
        Status
        Message
    end
    methods
        function set.TargetPose(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RobotState'};
            validateattributes(val, validClasses, validAttributes, 'GetTargetPoseResponse', 'TargetPose')
            obj.TargetPose = val;
        end
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'GetTargetPoseResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'GetTargetPoseResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.GetTargetPoseResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.GetTargetPoseResponse;
            obj.reload(strObj);
        end
    end
end
