
classdef ManageTrajectoryResponse < ros.Message
    %ManageTrajectoryResponse MATLAB implementation of niryo_one_msgs/ManageTrajectoryResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManageTrajectoryResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ce29d15e7d5703c5ad3c167dfb65a723' % The MD5 Checksum of the message definition
        PropertyList = { 'Trajectory' 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'trajectory' 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Trajectory' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Trajectory
        Status
        Message
    end
    methods
        function set.Trajectory(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.Trajectory'};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryResponse', 'Trajectory')
            obj.Trajectory = val;
        end
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ManageTrajectoryResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManageTrajectoryResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManageTrajectoryResponse;
            obj.reload(strObj);
        end
    end
end
