
classdef ManageSequenceResponse < ros.Message
    %ManageSequenceResponse MATLAB implementation of niryo_one_msgs/ManageSequenceResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ManageSequenceResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'aaa53fce535ae8c2e063d1fd74a644da' % The MD5 Checksum of the message definition
        PropertyList = { 'Sequence' 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'sequence' 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.niryo_one_msgs.Sequence' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Sequence
        Status
        Message
    end
    methods
        function set.Sequence(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.Sequence'};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceResponse', 'Sequence')
            obj.Sequence = val;
        end
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceResponse', 'Status');
            obj.Status = int32(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'ManageSequenceResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ManageSequenceResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ManageSequenceResponse;
            obj.reload(strObj);
        end
    end
end
