
classdef OpenGripperRequest < ros.Message
    %OpenGripperRequest MATLAB implementation of niryo_one_msgs/OpenGripperRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/OpenGripperRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'bcf0f25a53019052992fbcb00df9771a' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'OpenPosition' 'OpenSpeed' 'OpenHoldTorque' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'open_position' 'open_speed' 'open_hold_torque' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        OpenPosition
        OpenSpeed
        OpenHoldTorque
    end
    methods
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OpenGripperRequest', 'Id');
            obj.Id = uint8(val);
        end
        function set.OpenPosition(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OpenGripperRequest', 'OpenPosition');
            obj.OpenPosition = int16(val);
        end
        function set.OpenSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OpenGripperRequest', 'OpenSpeed');
            obj.OpenSpeed = int16(val);
        end
        function set.OpenHoldTorque(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'OpenGripperRequest', 'OpenHoldTorque');
            obj.OpenHoldTorque = int16(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.OpenGripperRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.OpenGripperRequest;
            obj.reload(strObj);
        end
    end
end
