
classdef PingDxlToolRequest < ros.Message
    %PingDxlToolRequest MATLAB implementation of niryo_one_msgs/PingDxlToolRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/PingDxlToolRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '527516197432b3d63ada52e8e4abaa34' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'Name' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'name' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        Name
    end
    methods
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PingDxlToolRequest', 'Id');
            obj.Id = uint8(val);
        end
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'PingDxlToolRequest', 'Name');
            obj.Name = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.PingDxlToolRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.PingDxlToolRequest;
            obj.reload(strObj);
        end
    end
end
