
classdef PullAirVacuumPumpRequest < ros.Message
    %PullAirVacuumPumpRequest MATLAB implementation of niryo_one_msgs/PullAirVacuumPumpRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/PullAirVacuumPumpRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '191580013becfd5fe2083349ac710b01' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'PullAirPosition' 'PullAirHoldTorque' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'pull_air_position' 'pull_air_hold_torque' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        PullAirPosition
        PullAirHoldTorque
    end
    methods
        function set.Id(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PullAirVacuumPumpRequest', 'Id');
            obj.Id = uint8(val);
        end
        function set.PullAirPosition(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PullAirVacuumPumpRequest', 'PullAirPosition');
            obj.PullAirPosition = int16(val);
        end
        function set.PullAirHoldTorque(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'PullAirVacuumPumpRequest', 'PullAirHoldTorque');
            obj.PullAirHoldTorque = int16(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.PullAirVacuumPumpRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.PullAirVacuumPumpRequest;
            obj.reload(strObj);
        end
    end
end
