
classdef RobotState < ros.Message
    %RobotState MATLAB implementation of niryo_one_msgs/RobotState
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/RobotState' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7def9c7c09d0c0932bec218f06669713' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'Rpy' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'rpy' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Point' ...
			 'ros.msggen.niryo_one_msgs.RPY' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        Rpy
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Point'};
            validateattributes(val, validClasses, validAttributes, 'RobotState', 'Position')
            obj.Position = val;
        end
        function set.Rpy(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.niryo_one_msgs.RPY'};
            validateattributes(val, validClasses, validAttributes, 'RobotState', 'Rpy')
            obj.Rpy = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.RobotState.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.RobotState;
            obj.reload(strObj);
        end
    end
end
