
classdef SetDigitalIORequest < ros.Message
    %SetDigitalIORequest MATLAB implementation of niryo_one_msgs/SetDigitalIORequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/SetDigitalIORequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '327c57b4c6002871c765eaf3cbe9ed8a' % The MD5 Checksum of the message definition
        PropertyList = { 'Pin' 'Value' } % List of non-constant message properties
        ROSPropertyList = { 'pin' 'value' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Pin
        Value
    end
    methods
        function set.Pin(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetDigitalIORequest', 'Pin');
            obj.Pin = uint8(val);
        end
        function set.Value(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetDigitalIORequest', 'Value');
            obj.Value = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.SetDigitalIORequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.SetDigitalIORequest;
            obj.reload(strObj);
        end
    end
end
