
classdef ToolCommand < ros.Message
    %ToolCommand MATLAB implementation of niryo_one_msgs/ToolCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/ToolCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '8f7e2396c11f11b006af359f471f8457' % The MD5 Checksum of the message definition
        PropertyList = { 'ToolId' 'CmdType' 'GripperCloseSpeed' 'GripperOpenSpeed' 'Activate' 'Gpio' } % List of non-constant message properties
        ROSPropertyList = { 'tool_id' 'cmd_type' 'gripper_close_speed' 'gripper_open_speed' 'activate' 'gpio' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ToolId
        CmdType
        GripperCloseSpeed
        GripperOpenSpeed
        Activate
        Gpio
    end
    methods
        function set.ToolId(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'ToolId');
            obj.ToolId = uint8(val);
        end
        function set.CmdType(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'CmdType');
            obj.CmdType = uint8(val);
        end
        function set.GripperCloseSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'GripperCloseSpeed');
            obj.GripperCloseSpeed = uint16(val);
        end
        function set.GripperOpenSpeed(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'GripperOpenSpeed');
            obj.GripperOpenSpeed = uint16(val);
        end
        function set.Activate(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'Activate');
            obj.Activate = logical(val);
        end
        function set.Gpio(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'ToolCommand', 'Gpio');
            obj.Gpio = uint8(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.ToolCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.ToolCommand;
            obj.reload(strObj);
        end
    end
end
