
classdef UpdateConveyorIdResponse < ros.Message
    %UpdateConveyorIdResponse MATLAB implementation of niryo_one_msgs/UpdateConveyorIdResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'niryo_one_msgs/UpdateConveyorIdResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '684cd572f268bd9685a29b0430c41747' % The MD5 Checksum of the message definition
        PropertyList = { 'Status' 'Message' } % List of non-constant message properties
        ROSPropertyList = { 'status' 'message' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
			 '' ...
			 } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Status
        Message
    end
    methods
        function set.Status(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'UpdateConveyorIdResponse', 'Status');
            obj.Status = uint8(val);
        end
        function set.Message(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'UpdateConveyorIdResponse', 'Message');
            obj.Message = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.niryo_one_msgs.UpdateConveyorIdResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.niryo_one_msgs.UpdateConveyorIdResponse;
            obj.reload(strObj);
        end
    end
end
